### ISSUE TITLE
Pattern test "reZ003v" not valid for Unicode 6.3.0 and up

### ISSUE THREAD

**Issue by bwrrp** [w3c/xsdtests#2]
It seems that code point 0x2308 (LEFT CEILING) has been changed from the "Sm" category to the "Ps" category starting from Unicode 6.3.0. This means it no longer matches the `\w` escape, causing the instance test to not validate.
There may be other characters that are affected, this was the first one I found, and seems to be the only test that fails on Unicode 12.1.0 due to category changes (block changes are another thing, but that is addressed in the spec).

**Comment by brunato** [comment]
Also the same for code point 0x2309 (RIGHT CEILING), changed from the "Sm" category to the "Pe" category. The other codes are right according to Unicode 12.1.0.

**Comment by michaelhkay** [comment]
Fixed.
