### ISSUE TITLE
XSD 1.1 xs:assert scope for complex content types

### ISSUE THREAD

**Issue by brunato** [w3c/xsdtests#4]
Doing a check on tests for XSD 1.1 assertions I'm not sure these two instance tests:

  - `<ts:instanceTest name="d4_3_15ii31i">`
  - `<ts:instanceTest name="d4_3_15ii32i">`

should be considered as invalid.

Referring to the first case (the 2nd is similar) the schema element that contains the assertion is:

```xml
<xs:complexType name="elementType2">
    <xs:sequence>			
         <xs:element name="subElement2" type="rootType" minOccurs="0" maxOccurs="unbounded"/>			
    </xs:sequence>		
    <xs:assert test="count(//ele1) eq 1"/>			
</xs:complexType>
```

that matches to the subelement *ele2* in the instance:

```xml
                        <ele2>			
				<subElement2>
					<ele1/>
				</subElement2>
			</ele2>
```

Within this context the test XPath expression of the assertion is true so the XML instance should be considered valid. But the annotation of test group says:

```xml
    <ts:annotation>
       <ts:documentation>"//" returns empty sequence</ts:documentation>
    </ts:annotation>
```
Who is failing on this evaluation? If I'm wrong why the ele1 leaf element is not belong to the scope of the assertion?

Thanks

**Comment by michaelhkay** [comment]
A path expression starting with "/" or "//" selects nothing if the context item is a node in a tree whose root is not a document node, but assertions are always evaluated against trees that are rooted at element nodes.

**Comment by brunato** [comment]
Well, I understand the reason of the invalidity now.
Thank you
