### ISSUE TITLE
Invalid regex patterns for XSD 1.0

### ISSUE THREAD

**Issue by brunato** [w3c/xsdtests#5]
Considering the qt3tests's test case _K2-MatchesFunc-16a_, and the [public report 21425](https://www.w3.org/Bugs/Public/show_bug.cgi?id=21425) about the split of results for XSD 1.0 and XSD 1.1, the following test cases should be marked as invalid for XSD 1.0:

```
reF20
reF21
reF22
reF23
reG26
reG27
reG28
reG29
reG30
reG31
reG32
reG33
reH19
reH20
reH21
```

**Comment by michaelhkay** [comment]
Please feel free to submit a pull request.

**Comment by pointsman** [comment]
While working with the xsdtests test suite I also stumbled about those tests. The by @brunato propsed standard marking of those tests in Regex_w3c.xml as

         <expected version="1.0" validity="invalid"/>
         <expected version="1.1" validity="valid"/>

would have helped me a lot in this "what is this" (aka wtf) moment. 

To prevent this for others in the future please consider applying the patch by @brunato.
